"""setup for dubfiv."""

from distutils.core import setup

setup(
    name="dubfiv",
    version="0.1",
    author="",
    author_email="",
    packages=["dubfiv", "two4two"],
    # package_dir={
    # "two4two.bias": "two4two/two4two",
    # },
    install_requires=[
        "autopep8",
        "b2",
        "cairosvg",
        "cairosvg",
        "flake8",
        "flake8-annotations",
        "flake8-docstrings",
        "flake8-import-order",
        "GPUtil",
        "imageio",
        "imgaug",
        "ipykernel",
        "ipywidgets",
        "jupyterlab",
        "jupyterlab-vim",
        "jupyterlab_code_formatter",
        "matplotlib>=3.4.0",
        "mypy",
        "numpy",
        "pandas",
        "pytest",
        "pytest-cov",
        "scipy",
        "seaborn",
        "spotlight @ git+https://github.com/maciejkula/spotlight.git@75f4c8c55090771b52b88ef1a00f75bb39f9f2a9#egg=spotlight",  # noqa
        "sklearn",
        "statsmodels",
        "torch",
        "torchvision",
        "tqdm",
        "typed-argument-parser",
        "types-toml",
        "wandb",
    ],
    python_requires=">=3.7",
    entry_points={
        "console_scripts": [
            "dubfiv_collect_runs=dubfiv.scripts.collect_runs:main",
            "dubfiv_dataset_configs=dubfiv.scripts.generate_dataset_configs:main",
            "dubfiv_export_user_study=dubfiv.scripts.export_user_study:main",
            "dubfiv_generate_figures=dubfiv.scripts.generate_figures:main",
            "dubfiv_model_summary=dubfiv.scripts.model_summary:main",
            "dubfiv_print_shapes=dubfiv.scripts.print_model_outputs:main",
            "dubfiv_supervised=dubfiv.train_supervised:main",
            "dubfiv_train=dubfiv.train:main",
            "dubfiv_supervised_analysis=dubfiv.scripts.supervised_analysis:main",
            "dubfiv_two4two_merge=dubfiv.scripts.merge_datasets:main",
            "two4two_render_dataset=two4two.cli_tool:render_dataset",
        ],
    },
)
